name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set Release Name
      run: |
        echo "TIME=$(date +"%Y%m%d%H%M%S")" >> $GITHUB_ENV
        echo "HASH=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV

    - name: Upload a Release Asset
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v0.0.${{ env.TIME }}
